notifications:
  email: false
git:
  quiet: true
  depth: 1
language: java
jdk: openjdk8
python: 3
addons:
  apt:
    update: true
    packages:
    - sudo
    - lsof
    - wget
    - bash
    - curl
    - jq
    - python3-dev
    - python3-pip
    - python3-six
    - python3-setuptools
install: true
before_install:
- export PATH=$HOME/.local/bin:$PATH
- pip3 install --user $(whoami) --upgrade pip >/dev/null # pip3 -> pip
- pip install --user $(whoami) --upgrade httpie >/dev/null 2>&1
- http --version --debug
#
- source <(curl -s https://raw.githubusercontent.com/daggerok/bash-functions/master/main.bash)
- stop_any 80 8001 8002 8080 5432
jobs:
  include:
  - stage: test
    jdk: openjdk8
    name: mvn test
    script: cd $TRAVIS_BUILD_DIR && ./mvnw
  - stage: test
    jdk: openjdk11
    name: mvn test openjdk11
    script: cd $TRAVIS_BUILD_DIR && ./mvnw
  - stage: test
    jdk: openjdk8
    name: integration tests
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw
    - java -jar $TRAVIS_BUILD_DIR/target/*.jar &
    - wait_for 8080
    - http :8080/user username=ololo id=00000000-0000-0000-0000-000000000000
    - http :8080/user/00000000-0000-0000-0000-000000000000
    - http :8080/user username=ololo id=00000000-0000-0000-0000-000000000000
    - http :8080 username=ololo id=00000000-0000-0000-0000-000000000000
    - stop_any 80
  - stage: test
    jdk: openjdk11
    name: integration tests openjdk11
    script:
    - cd $TRAVIS_BUILD_DIR && ./mvnw
    - java -jar $TRAVIS_BUILD_DIR/target/*.jar &
    - wait_for 8080
    - http :8080/user username=ololo id=00000000-0000-0000-0000-000000000000
    - http :8080/user/00000000-0000-0000-0000-000000000000
    - http :8080/user username=ololo id=00000000-0000-0000-0000-000000000000
    - http :8080 username=ololo id=00000000-0000-0000-0000-000000000000
    - stop_any 80
  - stage: test
    jdk: openjdk8
    name: mvn versions:display-property-updates
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
  - stage: test
    jdk: openjdk11
    name: mvn versions:display-property-updates (openjdk11)
    script: cd $TRAVIS_BUILD_DIR && ./mvnw versions:display-property-updates
cache:
  directories:
  - ~/.docker
  - ~/.m2
  packages: true
  pip: true
